apiVersion: v1
kind: Pod
metadata:
  name: {{test-pod-name}}
spec:
  #backoffLimit: 0
  #template:
  #  spec:
  volumes:
    - name: results
      hostPath:
        path: /run/desktop/mnt/host/d/results/export
        type: DirectoryOrCreate
  containers:
    - name: gatling-test
      image: localhost:5000/gatling-test-srv
      imagePullPolicy: Always
      volumeMounts:
        - name: results
          mountPath: /build/target/gatling/export
  restartPolicy: Never