apiVersion: v1
kind: Pod
metadata:
  name: "gatling-report-runner"
spec:
  volumes:
    - name: results
      hostPath:
        path: /run/desktop/mnt/host/d/results
        type: DirectoryOrCreate
  containers:
    - name: gatling-report
      image: localhost:5000/gatling-report-srv
      imagePullPolicy: Always
      volumeMounts:
        - name: results
          mountPath: /opt/gatling/results
  restartPolicy: Never